/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandarin.pkgfor.beginners;

/**
 *
 * @author glimp
 */
public class CharacterPage extends javax.swing.JFrame {

    /**
     * Creates new form CharacterPage
     */
    public CharacterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        AiBtn = new javax.swing.JButton();
        BuBtn = new javax.swing.JButton();
        DeBtn = new javax.swing.JButton();
        CanBtn = new javax.swing.JButton();
        GeBtn = new javax.swing.JButton();
        GuoBtn = new javax.swing.JButton();
        HenBtn = new javax.swing.JButton();
        HaoBtn = new javax.swing.JButton();
        HuanBtn = new javax.swing.JButton();
        LiangBtn = new javax.swing.JButton();
        MaBtn = new javax.swing.JButton();
        MeiBtn = new javax.swing.JButton();
        PiaoBtn = new javax.swing.JButton();
        QiuBtn = new javax.swing.JButton();
        RenBtn = new javax.swing.JButton();
        ShangBtn = new javax.swing.JButton();
        ShiBtn = new javax.swing.JButton();
        TaHeBtn = new javax.swing.JButton();
        TaItBtn = new javax.swing.JButton();
        TaSheBtn = new javax.swing.JButton();
        WanBtn = new javax.swing.JButton();
        TongBtn = new javax.swing.JButton();
        WoBtn = new javax.swing.JButton();
        XiBtn = new javax.swing.JButton();
        YiBtn = new javax.swing.JButton();
        You1Btn = new javax.swing.JButton();
        Yong = new javax.swing.JButton();
        You2Btn = new javax.swing.JButton();
        ZaoBtn = new javax.swing.JButton();
        ZhongBtn = new javax.swing.JButton();
        ZaiBtn = new javax.swing.JButton();
        NiBtn = new javax.swing.JButton();
        MenuBtn = new javax.swing.JButton();
        CanvasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        AiBtn.setText("Ai");
        AiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AiBtnActionPerformed(evt);
            }
        });

        BuBtn.setText("Bu");
        BuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuBtnActionPerformed(evt);
            }
        });

        DeBtn.setText("De");
        DeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeBtnActionPerformed(evt);
            }
        });

        CanBtn.setText("Can");
        CanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanBtnActionPerformed(evt);
            }
        });

        GeBtn.setText("Ge");
        GeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeBtnActionPerformed(evt);
            }
        });

        GuoBtn.setText("Guo");
        GuoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuoBtnActionPerformed(evt);
            }
        });

        HenBtn.setText("Hen");
        HenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HenBtnActionPerformed(evt);
            }
        });

        HaoBtn.setText("Hao");
        HaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaoBtnActionPerformed(evt);
            }
        });

        HuanBtn.setText("Huan");
        HuanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuanBtnActionPerformed(evt);
            }
        });

        LiangBtn.setText("Liang");
        LiangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiangBtnActionPerformed(evt);
            }
        });

        MaBtn.setText("Ma");
        MaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaBtnActionPerformed(evt);
            }
        });

        MeiBtn.setText("Mei");
        MeiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeiBtnActionPerformed(evt);
            }
        });

        PiaoBtn.setText("Piao");
        PiaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiaoBtnActionPerformed(evt);
            }
        });

        QiuBtn.setText("Qiu");
        QiuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QiuBtnActionPerformed(evt);
            }
        });

        RenBtn.setText("Ren");
        RenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenBtnActionPerformed(evt);
            }
        });

        ShangBtn.setText("Shang");
        ShangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShangBtnActionPerformed(evt);
            }
        });

        ShiBtn.setText("Shi");
        ShiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiBtnActionPerformed(evt);
            }
        });

        TaHeBtn.setText("Ta(he)");
        TaHeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaHeBtnActionPerformed(evt);
            }
        });

        TaItBtn.setText("Ta(it)");
        TaItBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaItBtnActionPerformed(evt);
            }
        });

        TaSheBtn.setText("Ta(she)");
        TaSheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaSheBtnActionPerformed(evt);
            }
        });

        WanBtn.setText("Wan");
        WanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WanBtnActionPerformed(evt);
            }
        });

        TongBtn.setText("Tong");
        TongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TongBtnActionPerformed(evt);
            }
        });

        WoBtn.setText("Wo");
        WoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WoBtnActionPerformed(evt);
            }
        });

        XiBtn.setText("Xi");
        XiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XiBtnActionPerformed(evt);
            }
        });

        YiBtn.setText("Yi");
        YiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YiBtnActionPerformed(evt);
            }
        });

        You1Btn.setText("You1");
        You1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                You1BtnActionPerformed(evt);
            }
        });

        Yong.setText("Yong");
        Yong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YongActionPerformed(evt);
            }
        });

        You2Btn.setText("You2");
        You2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                You2BtnActionPerformed(evt);
            }
        });

        ZaoBtn.setText("Zao");
        ZaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZaoBtnActionPerformed(evt);
            }
        });

        ZhongBtn.setText("Zhong");
        ZhongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZhongBtnActionPerformed(evt);
            }
        });

        ZaiBtn.setText("Zai");
        ZaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZaiBtnActionPerformed(evt);
            }
        });

        NiBtn.setText("Ni");
        NiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiBtnActionPerformed(evt);
            }
        });

        MenuBtn.setText("MainMenu");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });

        CanvasBtn.setText("TryItYourself");
        CanvasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanvasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GeBtn)
                        .addComponent(AiBtn))
                    .addComponent(HuanBtn)
                    .addComponent(PiaoBtn)
                    .addComponent(ShiBtn)
                    .addComponent(TongBtn)
                    .addComponent(YiBtn)
                    .addComponent(ZaoBtn))
                .addGap(43, 43, 43)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuBtn)
                    .addComponent(GuoBtn)
                    .addComponent(LiangBtn)
                    .addComponent(QiuBtn)
                    .addComponent(TaHeBtn)
                    .addComponent(WanBtn)
                    .addComponent(Yong)
                    .addComponent(ZhongBtn))
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CanBtn)
                    .addComponent(HaoBtn)
                    .addComponent(MaBtn)
                    .addComponent(RenBtn)
                    .addComponent(TaItBtn)
                    .addComponent(WoBtn)
                    .addComponent(You1Btn)
                    .addComponent(ZaiBtn))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NiBtn)
                    .addComponent(You2Btn)
                    .addComponent(XiBtn)
                    .addComponent(TaSheBtn)
                    .addComponent(ShangBtn)
                    .addComponent(MeiBtn)
                    .addComponent(HenBtn)
                    .addComponent(DeBtn))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(MenuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CanvasBtn))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuBtn)
                    .addComponent(CanvasBtn))
                .addGap(38, 38, 38)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AiBtn)
                    .addComponent(BuBtn)
                    .addComponent(CanBtn)
                    .addComponent(DeBtn))
                .addGap(48, 48, 48)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeBtn)
                    .addComponent(GuoBtn)
                    .addComponent(HaoBtn)
                    .addComponent(HenBtn))
                .addGap(51, 51, 51)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuanBtn)
                    .addComponent(LiangBtn)
                    .addComponent(MaBtn)
                    .addComponent(MeiBtn))
                .addGap(52, 52, 52)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PiaoBtn)
                    .addComponent(QiuBtn)
                    .addComponent(RenBtn)
                    .addComponent(ShangBtn))
                .addGap(48, 48, 48)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShiBtn)
                    .addComponent(TaHeBtn)
                    .addComponent(TaItBtn)
                    .addComponent(TaSheBtn))
                .addGap(47, 47, 47)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TongBtn)
                    .addComponent(WanBtn)
                    .addComponent(WoBtn)
                    .addComponent(XiBtn))
                .addGap(49, 49, 49)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YiBtn)
                    .addComponent(You1Btn)
                    .addComponent(Yong)
                    .addComponent(You2Btn))
                .addGap(47, 47, 47)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZaoBtn)
                    .addComponent(ZhongBtn)
                    .addComponent(ZaiBtn)
                    .addComponent(NiBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jInternalFrame1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuBtnActionPerformed
        new BuGif().setVisible(true);
    }//GEN-LAST:event_BuBtnActionPerformed

    private void HaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaoBtnActionPerformed
        new HaoGif().setVisible(true);
    }//GEN-LAST:event_HaoBtnActionPerformed

    private void TaSheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaSheBtnActionPerformed
        new TaSheGif().setVisible(true);
    }//GEN-LAST:event_TaSheBtnActionPerformed

    private void YongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YongActionPerformed
        new YongGif().setVisible(true);
    }//GEN-LAST:event_YongActionPerformed

    private void You1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_You1BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_You1BtnActionPerformed

    private void ZhongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZhongBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZhongBtnActionPerformed

    private void ZaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZaiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZaiBtnActionPerformed

    private void NiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NiBtnActionPerformed

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
        new Menu().setVisible(true);
    }//GEN-LAST:event_MenuBtnActionPerformed

    private void CanvasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanvasBtnActionPerformed
        new SwingPaint().show();
    }//GEN-LAST:event_CanvasBtnActionPerformed

    private void AiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AiBtnActionPerformed
        new AiGif().setVisible(true);
    }//GEN-LAST:event_AiBtnActionPerformed

    private void CanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanBtnActionPerformed
        new CanGif().setVisible(true);
    }//GEN-LAST:event_CanBtnActionPerformed

    private void DeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeBtnActionPerformed
        new DeGif().setVisible(true);
    }//GEN-LAST:event_DeBtnActionPerformed

    private void GeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeBtnActionPerformed
        new GeGif().setVisible(true);
    }//GEN-LAST:event_GeBtnActionPerformed

    private void GuoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuoBtnActionPerformed
        new GuoGif().setVisible(true);
    }//GEN-LAST:event_GuoBtnActionPerformed

    private void HenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HenBtnActionPerformed
        new HenGif().setVisible(true);
    }//GEN-LAST:event_HenBtnActionPerformed

    private void HuanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuanBtnActionPerformed
        new HuanGif().setVisible(true);
    }//GEN-LAST:event_HuanBtnActionPerformed

    private void LiangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiangBtnActionPerformed
        new LiangGif().setVisible(true);
    }//GEN-LAST:event_LiangBtnActionPerformed

    private void MaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaBtnActionPerformed
        new MaGif().setVisible(true);
    }//GEN-LAST:event_MaBtnActionPerformed

    private void MeiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeiBtnActionPerformed

    private void PiaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiaoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiaoBtnActionPerformed

    private void QiuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QiuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QiuBtnActionPerformed

    private void RenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RenBtnActionPerformed

    private void ShangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShangBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShangBtnActionPerformed

    private void ShiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShiBtnActionPerformed

    private void TaHeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaHeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaHeBtnActionPerformed

    private void TaItBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaItBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaItBtnActionPerformed

    private void TongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TongBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TongBtnActionPerformed

    private void WanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WanBtnActionPerformed

    private void WoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WoBtnActionPerformed

    private void XiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XiBtnActionPerformed

    private void YiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YiBtnActionPerformed

    private void You2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_You2BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_You2BtnActionPerformed

    private void ZaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZaoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZaoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AiBtn;
    private javax.swing.JButton BuBtn;
    private javax.swing.JButton CanBtn;
    private javax.swing.JButton CanvasBtn;
    private javax.swing.JButton DeBtn;
    private javax.swing.JButton GeBtn;
    private javax.swing.JButton GuoBtn;
    private javax.swing.JButton HaoBtn;
    private javax.swing.JButton HenBtn;
    private javax.swing.JButton HuanBtn;
    private javax.swing.JButton LiangBtn;
    private javax.swing.JButton MaBtn;
    private javax.swing.JButton MeiBtn;
    private javax.swing.JButton MenuBtn;
    private javax.swing.JButton NiBtn;
    private javax.swing.JButton PiaoBtn;
    private javax.swing.JButton QiuBtn;
    private javax.swing.JButton RenBtn;
    private javax.swing.JButton ShangBtn;
    private javax.swing.JButton ShiBtn;
    private javax.swing.JButton TaHeBtn;
    private javax.swing.JButton TaItBtn;
    private javax.swing.JButton TaSheBtn;
    private javax.swing.JButton TongBtn;
    private javax.swing.JButton WanBtn;
    private javax.swing.JButton WoBtn;
    private javax.swing.JButton XiBtn;
    private javax.swing.JButton YiBtn;
    private javax.swing.JButton Yong;
    private javax.swing.JButton You1Btn;
    private javax.swing.JButton You2Btn;
    private javax.swing.JButton ZaiBtn;
    private javax.swing.JButton ZaoBtn;
    private javax.swing.JButton ZhongBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
