/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandarin.pkgfor.beginners;

/**
 *
 * @author glimp
 */
public class PinyinPage extends javax.swing.JFrame {

    /**
     * Creates new form CharacterPage
     */
    public PinyinPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        wobtn = new javax.swing.JButton();
        NiBtn = new javax.swing.JButton();
        QuBtn = new javax.swing.JButton();
        ZuoBtn = new javax.swing.JButton();
        ShangBtn = new javax.swing.JButton();
        ZouBtn = new javax.swing.JButton();
        ZaiBtn = new javax.swing.JButton();
        CanBtn = new javax.swing.JButton();
        LiuBtn = new javax.swing.JButton();
        BaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        wobtn.setText("Wo");

        NiBtn.setText("Ni");

        QuBtn.setText("qu");

        ZuoBtn.setText("Zuo");
        ZuoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZuoBtnActionPerformed(evt);
            }
        });

        ShangBtn.setText("shang");

        ZouBtn.setText("zou");
        ZouBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZouBtnActionPerformed(evt);
            }
        });

        ZaiBtn.setText("zai");

        CanBtn.setText("can");
        CanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanBtnActionPerformed(evt);
            }
        });

        LiuBtn.setText("liu");
        LiuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiuBtnActionPerformed(evt);
            }
        });

        BaBtn.setText("ba");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ShangBtn)
                        .addComponent(QuBtn)
                        .addComponent(wobtn))
                    .addComponent(ZaiBtn)
                    .addComponent(LiuBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NiBtn)
                    .addComponent(ZuoBtn)
                    .addComponent(ZouBtn)
                    .addComponent(CanBtn)
                    .addComponent(BaBtn))
                .addGap(180, 180, 180))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wobtn)
                    .addComponent(NiBtn))
                .addGap(93, 93, 93)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuBtn)
                    .addComponent(ZuoBtn))
                .addGap(79, 79, 79)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShangBtn)
                    .addComponent(ZouBtn))
                .addGap(54, 54, 54)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZaiBtn)
                    .addComponent(CanBtn))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaBtn)
                    .addComponent(LiuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(540, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jInternalFrame1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZuoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZuoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZuoBtnActionPerformed

    private void ZouBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZouBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZouBtnActionPerformed

    private void CanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanBtnActionPerformed

    private void LiuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LiuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinyinPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinyinPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinyinPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinyinPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinyinPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BaBtn;
    private javax.swing.JButton CanBtn;
    private javax.swing.JButton LiuBtn;
    private javax.swing.JButton NiBtn;
    private javax.swing.JButton QuBtn;
    private javax.swing.JButton ShangBtn;
    private javax.swing.JButton ZaiBtn;
    private javax.swing.JButton ZouBtn;
    private javax.swing.JButton ZuoBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton wobtn;
    // End of variables declaration//GEN-END:variables
}
